### ISSUE TITLE
ผมแปลบทที่ 2 แล้วครับ

### ISSUE THREAD

**Issue by pallat** [git2ra/progit2#2]
แปลบทที่ 2 ครับ

**Comment by Nann** [comment]
บทที่ 2 แปลเสร็จแล้ว Close Issues เลยไหมครับ เดี๋ยวคนเข้ามาเห็นแล้วคิดว่ายังแปลไม่เสร็จครับ?

**Comment by roofimon** [comment]
OK ครับ
